accounts/urls.py
from django.urls import path
from . import views 

app_name = 'account'

urlpatterns = [
    path('', views.account, name='account'),
]

alineter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('auth/', include('auth_page.urls')),
    path('blog/', include('blog.urls')),  
    path('cart/', include('cart.urls')),
    path('company/', include('company.urls')),  
    path('company/policy/', include('company_policy.urls')),  
    path('', include('home.urls')),  
    path('store/', include('store.urls'))
]


from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# ERR_HANDLER URL
from django.conf.urls import handler404, handler403, handler404, handler500

handler400 = 'ERROR_HANDLER.views.err_400'
handler403 = 'ERROR_HANDLER.views.err_403'
handler404 = 'ERROR_HANDLER.views.err_404'
handler500 = 'ERROR_HANDLER.views.err_500'

blog/urls.py
from django.urls import path
from . import views 

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart, name='cart'),
	path('fetch-cart/', views.fetch_cart, name='fetch_cart'),
	path('update/quantity/', views.update_quantity, name='update_quantity'),
]

company/urls.py
from django.urls import path
from . import views 

app_name = 'company'

urlpatterns = [
    path('', views.redirect_default, name='redirect_default'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('feedback/', views.write_about_us, name='write_about_us'),
    path('fetch-faq/', views.fetch_faq, name='fetch_faq'),
]

home/urls.py
from django.urls import path
from . import views 

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('company_reviews/', views.company_reviews, name='company_reviews'),
    path('reviews_stats/', views.reviews_stats, name='reviews_stats')
]

store/urls.py
from django.urls import path
from . import views 

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
]

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import get_user_model
from auth_page.models import Customer
User = get_user_model()

# Models
from company.models import CompanyReview

# Decorators
from cookie.decorators import check_login_cookie

# Python Import
# import json


# from accounts.decorators import check_login_cookie

@check_login_cookie
def home(request):
	context = {}

	# u = User.objects.get(email=request.user.email)
	# print(u.customer.mobile)

	# print(request.user.customer.mobile)
	# print("img: ",type(request.user.customer.profile_pic))

	# if request.user.customer.profile_pic:
	# 	print("image there")
	# else:
	# 	print("no image there")

	return render(request, 'home/index.html', context)



def company_reviews(request):
	if request.POST:
		reviews = CompanyReview.objects.all().filter(highlight=True)[:12] # 12 highlighted reviews only

		reviewers = [] # contains the list of reviewers and their detail

		for rev in reviews:
			reviewer = {} # detail of one reviewer
			reviewer['name'] = rev.user.get_full_name()
			
			if rev.user.customer.profile_pic:
				reviewer['img'] = rev.user.customer.profile_pic.url
			else:
				reviewer['img'] = '/static/images/alineter/avatar/avatar.png'
			
			review_detail = {}
			review_detail['content'] = rev.review
			review_detail['rating'] = rev.rating
			
			reviewer['review'] = review_detail

			reviewers.append(reviewer)

		return JsonResponse(reviewers, safe=False)
	return HttpResponse("Something went wrong")



def reviews_stats(request):
	if request.POST:
		import math

		reviews = CompanyReview.objects.all()
		num_reviews = len(reviews)
		
		stars = 0
		for rev in reviews:
			stars = stars + rev.rating
		total_rating = math.ceil(stars/num_reviews) # [stars/(num_reviews*5)]*5

		stats = {
			'num_of_reviews': num_reviews,
			'total_rating': total_rating
		}

		return JsonResponse(stats, safe=False)
	return HttpResponse('Something went wrong')






"""

# formation of company review json
[
	{
		name : "Mohit Kumar",
		img : "https://i.imgur.com/jQWThIn.jpg",
		review : {
			content : "Some quick example text to build on the card title and make up the bulk of the card's content.",
			rating : 3.5
		}
	},
	{
		name : "Caye Henry",
		img : "https://i.imgur.com/QptVdsp.jpg",
		review : {
			content : "Some quick example text to build on the card title and make up the bulk of the card's content.\n\nSome quick example text to build on the card title and make up the bulk of the card's content.",
			rating : 4.5
		}
	}
]


>>> from django.contrib.auth import get_user_model
>>> from django.contrib.auth.models import Group
>>> User = get_user_model()

>>> u1 = User.objects.get(email="mahitkumar166@gmail.com")
>>> u1  --> <User: mahitkumar166@gmail.com>

>>> gall = Group.objects.all()
>>> gall
<QuerySet [<Group: customer>, <Group: employee>, <Group: admin>]>
>>> g1.name  --> 'customer'

>>> u1.groups  --> <django.db.models.fields.related_descriptors.create_forward_many_to_many_manager.<locals>.ManyRelatedManager object at 0x045AC850>

>>> u1.groups.all()  --> <QuerySet [<Group: customer>]>
>>> u1.groups.all()[0].name  --> 'customer'



# SET EXPIRY OF SESSION
if request.GET:
		request.session['fav-lang'] = 'javascript'
		request.session.set_expiry(120)
	print(request.session.get('fav-lang'))


# SET SIMPLE COOKIE
if request.GET:
		# set cookie
		print("setting cookie")
		response = redirect("home:home")
		response.set_cookie('dataflair', 'Hello this is your cookies', max_age = None)
		return response
	try:
		request.COOKIES.get('dataflair')
	except:
		print("no cookies")
	else:
		print(request.COOKIES.get('dataflair'))


# SET COOKIE

import datetime
from django.conf import settings

def set_cookie(response, key, value, days_expire=7):
	if days_expire is None:
		max_age = 365 * 24 * 60 * 60 # one year in seconds
	else:
		max_age = days_expire*24*60*60 # in seconds

	expires = datetime.datetime.strftime(
			datetime.datetime.now() + datetime.timedelta(seconds=max_age),
			"%a, %d-%b-%Y %H:%M:%S"
	)

	response.set_cookie(
		key=key,
		value=value,
		max_age=max_age,
		expires=expires,
		domain=settings.SESSION_COOKIE_DOMAIN,
		secure=settings.SESSION_COOKIE_SECURE or None,
	)

	return response

def home(request):
	if request.GET:
			response = redirect('home:home')
			return set_cookie(response, 'eryu-dsfh-sadj-sdss', [1, 2, 3, 4]) # product_id , product_count

		if request.COOKIES.get('visit') is not None:
			# cookie is already set
			print("cookie is set")
			print("VISIT: ",request.COOKIES.get('eryu-dsfh-sadj-sdss'))
		else:
			# cookie is not set
			print("cookie is not set")

	return render(request, 'home/index.html')

"""

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}

  {% endblock title %}

  <meta link-colorarset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#1C1C1C">


  <!-- SEO -->
  {% block seo_metatag %}

  {% endblock seo_metatag %}


  <!-- BOOTSTRAP AND JQUERY -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

  <!-- SCROLL REVEAL LINK -->
  <script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>

  <!-- FONT AWESOME LINK -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!--GOOGLE FONTS-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;300;400;600&family=Nunito:wght@200;300;400;700;800&family=Open+Sans:wght@300;400;600;800&family=Roboto:wght@100;300;400&display=swap" rel="stylesheet">

  <!-- FAVICON -->
  <link rel="icon" href="/static/images/alineter/alineter-b.png">

  <!-- EXTERNAL CSS LINKS -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?{% now 'U' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/navigation.css' %}?{% now 'U' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/input-styles.css' %}?{% now 'U' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}?{% now 'U' %}">

  <!-- Order of this should be maintained -->
  {% block css_link %}

  {% endblock css_link %}

  <link rel="stylesheet" type="text/css" href="{% static 'css/input-validation.css' %}?{% now 'U' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/utility.css' %}?{% now 'U' %}">



  <style type="text/css">

    /* Loading Animation */

    #loading {
      width:100%;
      height:100vh;
    }
    .loading-wrapper {
      position:relative;
      top:50%;
      transform:translateY(-50%) scale(1);
      -webkit-transform:translateY(-50%) scale(1);
    }
    .cube-spinner-nm {
      transform:scale(1);
      -webkit-transform:scale(1);
    }
    .cube-spinner-lg {
      transform:scale(1.1);
      -webkit-transform:scale(1.1);
    }
    .cube-spinner-md {
      transform:scale(0.8);
      -webkit-transform:scale(0.8);
    }
    .cube-spinner-sm {
      transform:scale(0.6);
      -webkit-transform:scale(0.6);
    }
    .spinner {
      position:relative;
      width:60px;
      height:60px;
      left:50%;
      transform:translateX(-50%);
      -webkit-transform:translateX(-50%);
    }
    .cube {
      position:absolute;
      top:0;
      left:0;
      width:20px;
      height:20px;
      border:0;
      border-radius:2px;
      -webkit-animation: loading-cubemove 1.8s infinite ease-in-out;
      animation: loading-cubemove 1.8s infinite ease-in-out;
    }
    .cube-1 {
      background-color:#F15A24;
    }
    .cube-2 {
      background-color:#000000;
      -webkit-animation-delay: -0.9s;
      animation-delay: -0.9s;

    }
    @-webkit-keyframes loading-cubemove {
      25% { 
        -webkit-transform:translateX(42px) rotate(-90deg) scale(0.5);
      } 50% { 
        -webkit-transform:translateX(42px) translateY(42px) rotate(-180deg) ;
      } 75% { 
        -webkit-transform:translateX(0px) translateY(42px) rotate(-270deg) scale(0.5);
      } 100% { 
        -webkit-transform:rotate(-360deg);
      }
    }
    @keyframes loading-cubemove {
      25% { 
        transform:translateX(42px) rotate(-90deg) scale(0.5); 
        -webkit-transform:translateX(42px) rotate(-90deg) scale(0.5);
      } 50% { 
        transform:translateX(42px) translateY(42px) rotate(-179deg);
        -webkit-transform:translateX(42px) translateY(42px) rotate(-179deg);
      } 50.1% { 
        transform:translateX(42px) translateY(42px) rotate(-180deg); 
        -webkit-transform:translateX(42px) translateY(42px) rotate(-180deg);
      } 75% { 
        transform:translateX(0px) translateY(42px) rotate(-270deg) scale(0.5); 
        -webkit-transform:translateX(0px) translateY(42px) rotate(-270deg) scale(0.5);
      } 100% { 
        transform:rotate(-360deg); 
        -webkit-transform:rotate(-360deg);
      }
    }

    section#body {
      display:none;
      -webkit-animation-name: increaseOpacity;
      -webkit-animation-duration:1.3s;
      animation-name: increaseOpacity;
      animation-duration: 0.5s;
      animation-timing-function: ease-in;
    }
    @-webkit-keyframes increaseOpacity {
      from {
        opacity:0 
      } 
      to {
        opacity:1 
      }
    }
    @keyframes increaseOpacity { 
      from {
        opacity:0 
      } 
      to {
        opacity:1 
      }
    }

  </style>
 
</head>

<body>

  <section id="loading">
    <div class="loading-wrapper">
      <div class="spinner">
        <div class="cube cube-1"></div>
        <div class="cube cube-2"></div>
      </div>
    </div> 
  </section>

  

  <section id="body">

    {% include 'home/nav.html' %}

    
    <section id="page-content" class="position-relative">

      {% block page_content %}

      {% endblock page_content %}

      
      {% include 'home/footer.html' %}

    </section><!--Page Content-->

  
  </section><!--Body-->


<script type="text/javascript" src="{% static 'js/activate-page.js' %}?{% now 'U' %}"></script>

<script type="text/javascript" src="{% static 'js/sliding-navbar.js' %}?{% now 'U' %}"></script>
<script type="text/javascript" src="{% static 'js/scroll-reveal.js' %}?{% now 'U' %}"></script>
<script type="text/javascript" src="{% static 'js/utility.js' %}?{% now 'U' %}"></script>
<script type="text/javascript" src="{% static 'js/verification.js' %}?{% now 'U' %}"></script>

<script type="text/javascript" src="{% static 'js/detect-mobile.js' %}?{% now 'U' %}"></script>

{% block js_script_link %}

{% endblock js_script_link %}


</body>

</html>


home/templates/home/footer.html

<!-- ================== FOOTER SECTION ==================== -->

<!-- Button to Scroll Up -->
<div class="container text-center">
  <div class="scroll-horizontal to-top">
      <button type="button" class="scroll-btn btn pt-2 ripple-opacity-d" page-scroll="top" onclick="slideUp()" ><i class="fa fa-caret-up"></i></button>
  </div>
</div>

<script>
  /* Slide the page back to top */
  function slideUp() {
    let windowHeight = $(window).height();
    $("html,body").animate({scrollTop:-windowHeight},1000);
  }
</script>

<footer id="footer" class="w-100">
  <div class="container-fluid pt-4 pb-4 txt-light">
    <div class="row m-0 p-0">

      <div class="col-lg-6 col-md-6 col-sm-12 col-footer text-center">
        <div class="d-flex flex-column">
          <div class="section first">
            <h4 class="title">Ready For Every Moment</h4>
          </div>
          <div class="section second">

            <form method="post" action=".">
              <div class="d-flex flex-column">
                <div class="d-flex justify-content-center">
                  <input type="email" name="subscriber-email" id="subscriber-email" class="input--s2 subscriber-email" required spellcheck="false" onkeyup="ifValid(this, 2)" placeholder="Enter Email" />
                  <div class="input-group-append" style="z-index:0">
                    <button type="button" name="subscribe-btn" class="btn subscribe-btn">SUBSCRIBE</button>
                  </div>
                </div>
              </div>
            </form>

          </div>
          <div class="section third">
            <h5 class="title">Follow Us</h5>
            <a href="https://twitter.com/alineterindia" class="social-link"><i class="fa fa-twitter-square"></i></a>
            <a href="https://www.instagram.com/alineterindia/" class="social-link"><i class="fa fa-instagram"></i></a>
            <a href="https://www.facebook.com/alineterindia" class="social-link"><i class="fa fa-facebook-square"></i></a>
            <a href="https://www.linkedin.com/company/alineter" class="social-link"><i class="fa fa-linkedin-square"></i></a>
          </div>
        </div>
      </div>

      <div class="col-lg-6 col-md-6 col-sm-12 col-footer m-0">
        <div class="row">
          <div class="col-6">
            <div class="d-flex flex-column">
              <div class="d-flex flex-column section first">
                <div>
                  <a href="{% url 'policy:ordering_terms' %}" class="link s-1">Ordering & Payment Terms</a>
                </div>
                <div>
                  <a href="#" class="link s-1">Shipping</a>
                </div>
                <div>
                  <a href="#" class="link s-1">Sizing Guide</a>
                </div>
                <div>
                  <a href="{% url 'company:faq' %}" class="link s-1">FAQs</a>
                </div>
              </div>
              <div class="d-flex flex-column section second">
                <div>
                  <a href="{% url 'policy:terms_condition' %}" class="link s-1">Privacy Policy</a>
                </div>
                <div>
                  <a href="{% url 'policy:terms_condition' %}" class="link s-1">Terms of Use</a>
                </div>
                <div>
                  <a href="{% url 'policy:cancellation_refund' %}" class="link s-1">Return Policy</a>
                </div>
                <div>
                  <a href="{% url 'policy:cancellation_refund' %}" class="link s-1">Cancellation & Refund</a>
                </div>
              </div>
            </div>                  
          </div>
          <div class="col-6 m-0" style="overflow:hidden;">
            <div class="d-flex flex-column">
              <div class="d-flex flex-column section first">
                <div class="row m-0 mb-2 contact-us">
                  <div class="col-2 p-0">
                    <i class="fa fa-envelope"></i>
                  </div>
                  <div class="col-10 p-0">
                    <a href="mailto:info@alineter.com" class="link s-3">info@alineter.com</a>
                  </div>
                </div>
                <div class="row m-0 contact-us">
                  <div class="col-2 p-0">
                    <i class="fa fa-phone-square"></i>
                  </div>
                  <div class="col-10 p-0">
                    <a href="tel:8895738760" class="link s-3">(91) 8895738760</a>
                  </div>
                </div>
              </div>
              <div class="section second">
                <h5 class="title">Accepted Payments</h5>
                <div class="d-flex flex-wrap payment-method">
                  <img src="/static/images/alineter/cc-amex.png" width=40 height=20 class="img-fluid"/>
                  <img src="/static/images/alineter/cc-mastercard.png" width=40 height=20 class="img-fluid"/>
                  <img src="/static/images/alineter/cc-visa.png" width=40 height=20 class="img-fluid"/>
                  <!-- <img src="static/images/alineter/cc-cod.png" width=40 height=20 class="img-fluid"/> -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
  <div class="copyright-wrapper text-center">
    <div class="container-fluid txt-light">
      <small>
        <span>&copy;2020-<span id="copyright-year"></span></span>
        <span><a href="{% url 'home:home' %}" class="link s-2">Alineter</a></span>
        <span>All Rights Reserved.</span>
        <span><a href="{% url 'policy:terms_condition' %}" class="link s-2">Terms of Use</a></span>
        <span>|</span>
        <span><a href="{% url 'policy:terms_condition' %}" class="link s-2">Privacy Policy</a></span>
      </small>
    </div>
   <script>
      let year=new Date().getFullYear().toString().slice(2);
      document.getElementById("copyright-year").innerHTML = year;
    </script>
  </div>
</footer>


<!--

Shipping and sizing guide URL is not there

-->

home/templates/home/nav.html

<!-- ============ NAVIGATION BAR SECTION =========== -->   

<nav id="navigation" class="navbar fixed-top navigation-init">
  <div class="nav-left">
    <a href="{% url 'home:home' %}" class="navbar-brand">
      <div class="d-flex flex-column p-0 text-center align-items-center">
        <img src="/static/images/alineter/alineter-b.png" id="brand-logo" width=47 height=47 alt="alineter logo"/>
        <small class="logo-text">ALINETER</small>
      </div>
    </a>
  </div>
  <div class="nav-right ml-auto">
    <ul class="d-flex my-auto" style="list-style:none">
      <li class="nav-item show-on-lg item-1 my-auto mr-1">
        <a href="{% url 'store:store' %}" class="nav-link">Store</a>
      </li>
      <li class="nav-item show-on-lg item-2 my-auto mr-1">
        <a href="{% url 'blog:blog' %}" class="nav-link">Blogs</a>
      </li>
      <li class="nav-item show-on-lg item-3 dropdown mr-2 my-auto">
        <button class="nav-link dropdown-toggler btn" id="more-section-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          More&nbsp;<span class="fa fa-caret-down"></span>
        </button>
        <div class="dropdown-menu shadow m-0 pl-0 pr-0" aria-labelledby="more-section-dropdown">
          <a class="nav-link dropdown-item" href="{% url 'company:about' %}"><span class="fa fa-address-card">&nbsp;</span>About Us</a>
          <a class="nav-link dropdown-item" href="{% url 'company:contact' %}"><span class="fa fa-paper-plane">&nbsp;</span>Contact Us</a>
          <a class="nav-link dropdown-item" href="{% url 'company:faq' %}"><span class="fa fa-question-circle">&nbsp;</span>FAQs</a>
          <a class="nav-link dropdown-item" href="{% url 'company:write_about_us' %}"><span class="fa fa-pencil">&nbsp;</span>Write About Us</a>
          <a class="nav-link dropdown-item" href="{% url 'policy:terms_condition' %}"><span class="fa fa-file">&nbsp;</span>Terms of Use</a>
          <a class="nav-link dropdown-item" href="{% url 'policy:ordering_terms' %}"><span class="fa fa-file">&nbsp;</span>Ordering Terms</a>
          <a class="nav-link dropdown-item" href="{% url 'policy:cancellation_refund' %}"><span class="fa fa-undo">&nbsp;</span>Cancellation & Refund</a>
          
          {% if not request.user.is_authenticated %}
            <a href="{% url 'auth:login' %}" class="nav-link dropdown-item"><span class="fa fa-sign-in">&nbsp;</span>Login</a>
          {% else %}
            <a href="#logout-modal" class="nav-link dropdown-item" data-toggle="modal"><span class="fa fa-sign-out">&nbsp;</span>Logout</a>
          {% endif %}
        
        </div>
      </li>
      <li class="nav-item mr-3 my-auto user-func">
        <div class="d-flex">
          
          {% if not request.user.is_authenticated %}
            <a href="{% url 'auth:signup' %}" class="btn btn-o-tertiary ripple-opacity-l rounded pl-4 pr-4">Sign Up</a>
          {% else %}
            <!-- when user is logged in -->
            <a href="{% url 'account:account' %}" class="nav-link">
              <span class="fa fa-user-circle-o txt-tertiary" style="font-size:1.3rem"></span>
            </a>

            <a href="{% url 'cart:cart' %}" class="nav-link">
              <span class="fa fa-opencart txt-tertiary">&nbsp;<span>0</span></span>
            </a>
          {% endif %}

        </div>
      </li> 
      <li class="nav-item show-on-sm my-auto">
        <button type="button" class="btn toggler-btn ripple-opacity-d" onclick="opennav()">
          <div class="bar bar-1"></div>
          <div class="bar bar-2"></div>
        </button> 
      </li>
    </ul>
  </div>

</nav>


<!-- ======== SLIDE NAVIGATION ========== -->

<section id="slide-navigation">
  <div class="container-fluid w-100 h-100 position-relative">
    <div class="slidenav-wrapper w-100">

      <div class="user-section text-center sticky-top fill-tertiary txt-light">

        <div class="user-section-main">
          <!--Nav Controller-->
          <div class="nav-controller">
              <button onclick="closenav()" class="btn close-sidenav"><span class="fa fa-times"></span></button>
          </div>

          <div class="user-section-wrapper">
            <div class="user-info d-flex flex-column">
              <div class="mr-3 my-auto pfimg-holder">

                  <img 
                    src="{% if not request.user.is_authenticated or not request.user.customer.profile_pic %}/static/images/alineter/avatar/avatar.png{% else %}/static{{ request.user.customer.profile_pic.url }}{% endif %}" class="pfImg img-cover" alt="{% if not request.user.is_authenticated %}Alineter avatar img{% else %}{{ request.user.username }} profile-pic{% endif %}" />

              </div>
              <div class="my-auto">
                
                <p class="lead txt-light user-name">Hey,&nbsp; 
                  {% if not request.user.is_authenticated or not request.user.first_name %}
                    User
                  {% else %}
                    {{ request.user.first_name }}
                  {% endif %}
                </p>
                
              </div>
            </div>
            <div class="user-function">
              <div class="d-flex justify-content-between">
                
                {% if not request.user.is_authenticated %}
                  <a href="{% url 'auth:signup' %}" class="user-function--link fancy-effects slide_line"><span class="fa fa-id-badge"></span>&nbsp;Create Account</a>
                  <a href="{% url 'auth:login' %}" class="user-function--link fancy-effects slide_line"><span class="fa fa-sign-in"></span>&nbsp;Login</a>
                {% else %}
                  <a href="{% url 'account:account' %}" class="user-function--link fancy-effects slide_line"><span class="fa fa-user"></span>&nbsp;My Account</a>
                  <a href="#logout-modal" class="user-function--link fancy-effects slide_line" data-toggle="modal"><span class="fa fa-sign-in"></span>&nbsp;Logout</a>
                {% endif %}

              </div>
            </div>
          </div>
        </div>

      </div>        

      <div class="site-links p-0 pb-5">
        <a href="{% url 'home:home' %}" class="nav-link"><span class="fa fa-home"></span>&nbsp;&nbsp;Home</a>
        <a href="{% url 'store:store' %}" class="nav-link"><span class="fa fa-shopping-bag"></span>&nbsp;&nbsp;Store</a>
        <a href="{% url 'blog:blog' %}" class="nav-link"><span class="fa fa-picture-o"></span>&nbsp;&nbsp;Blogs</a>
        <a href="{% url 'company:about' %}" class="nav-link"><span class="fa fa-address-card"></span>&nbsp;&nbsp;About Us</a>
        <a href="{% url 'company:contact' %}" class="nav-link"><span class="fa fa-paper-plane"></span>&nbsp;&nbsp;Contact Us</a>
        <a href="{% url 'company:faq' %}" class="nav-link"><span class="fa fa-question-circle"></span>&nbsp;&nbsp;FAQ</a>
        <a href="{% url 'company:write_about_us' %}" class="nav-link"><span class="fa fa-pencil"></span>&nbsp;&nbsp;Write About Us</a>
        <a href="{% url 'policy:terms_condition' %}" class="nav-link"><span class="fa fa-file"></span>&nbsp;&nbsp;Terms of Use</a>
        <a href="{% url 'policy:ordering_terms' %}" class="nav-link"><span class="fa fa-file"></span>&nbsp;&nbsp;Ordering Terms</a>
        <a href="{% url 'policy:cancellation_refund' %}" class="nav-link"><span class="fa fa-undo"></span>&nbsp;&nbsp;Cancellation & Refund</a>
      </div>
    </div>
  </div>
</section>

<!-- OVERLAY EFFECT NAVIGATION -->
<section id="overlay-effect" onclick="closenav()">
</section>


{% if request.user.is_authenticated %}
  <!-- Logout modal -->
  <div class="modal fade" id="logout-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <p><b>Are you sure you want to logout?</b></p>
          <div class="text-left">
            <a href="{% url 'auth:logout' %}" class="btn btn-i-primary"><span class="fa fa-sign-in">&nbsp;</span>Logout</a>
            <button type="button" class="btn btn-o-light ml-2" data-dismiss="modal"><span>&times;&nbsp;</span>Cancel</button>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endif %}

<!--

store page

-->