alineter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('auth/', include('auth_page.urls')),
    path('blog/', include('blog.urls')),  
    path('cart/', include('cart.urls')),
    path('company/', include('company.urls')),  
    path('company/policy/', include('company_policy.urls')),  
    path('', include('home.urls')),  
    path('store/', include('store.urls'))
]


from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# ERR_HANDLER URL
from django.conf.urls import handler404, handler403, handler404, handler500

handler400 = 'ERROR_HANDLER.views.err_400'
handler403 = 'ERROR_HANDLER.views.err_403'
handler404 = 'ERROR_HANDLER.views.err_404'
handler500 = 'ERROR_HANDLER.views.err_500'

auth_page/urls.py
from django.urls import path
from . import views 

app_name = 'auth'

urlpatterns = [
    path('', views.redirect_default, name='redirect_default'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('set-pic/', views.set_profilepic, name='set_profile_pic'),
    path('verify-account/', views.otp_verification, name='otp_verification'),
    path('delete-account/', views.delete_account, name='delete_account')
]

blog/urls.py
from django.urls import path
from . import views 

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
]

company/urls.py
from django.urls import path
from . import views 

app_name = 'company'

urlpatterns = [
    path('', views.redirect_default, name='redirect_default'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('feedback/', views.write_about_us, name='write_about_us'),
    path('fetch-faq/', views.fetch_faq, name='fetch_faq'),
]

company_policy/urls.py
from django.urls import path
from . import views 

app_name = 'policy'

urlpatterns = [
    path('', views.redirect_default, name='redirect_default'),
    path('cancellation-refund/', views.cancellation_refund, name='cancellation_refund'),
    path('terms-condition/', views.terms_condition, name='terms_condition'),
    path('ordering-terms/', views.ordering_terms, name='ordering_terms')
]

store/urls.py
from django.urls import path
from . import views 

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
]

company/models.py
from django.db import models
from django.utils.timesince import timesince
from django.contrib.auth import get_user_model
User = get_user_model()

# 3rd party import
from PIL import Image
from ckeditor.fields import RichTextField


def profilepic_directory_path(instance, filename):
	ext = filename.split('.')[1]
	username = ''.join(instance.name.split(' '))
	filename = f'{username}.{ext}'

	return f'alineter/founder/{filename}'


class Company(models.Model):
	name = models.CharField(verbose_name='Company Name', max_length=15)
	tag = models.CharField(verbose_name='Company Tag', max_length=255)
	active = models.BooleanField(verbose_name='Company Status', default=True)
	website = models.URLField(verbose_name='Company Website', max_length=50)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'Company'


class CompanyInfo(models.Model):
	MODES = (
		('public', 'Public'),
		('private', 'Private'),
		('joint', 'Joint')
	)
	company = models.OneToOneField(Company, on_delete=models.CASCADE)
	full_name = models.CharField(verbose_name='Company Fullname', max_length=100)
	cin = models.CharField(verbose_name='CIN', max_length=100)
	registration_number = models.CharField(verbose_name='Registration Number', max_length=20)
	founded = models.DateTimeField(verbose_name='Founded In')
	mode = models.CharField(verbose_name='Company Mode', choices=MODES, max_length=20)
	company_category = models.CharField(verbose_name='Company Category', max_length=100)
	company_subcategory = models.CharField(verbose_name='Company Subcategory', max_length=100)
	company_activity = models.TextField(verbose_name='Company Activity')
	members = models.IntegerField(verbose_name='Company Members', default=2)

	def __str__(self):
		return self.full_name

	def get_age(self):
		return timesince(self.founded)

	class Meta:
		verbose_name_plural = 'Company info'


class CompanyAddress(models.Model):
	company = models.OneToOneField(Company, on_delete=models.CASCADE)
	street = models.TextField(verbose_name='Street Address')
	city = models.CharField(verbose_name='City', max_length=40)
	pin = models.CharField(verbose_name='PIN', max_length=6)
	district = models.CharField(verbose_name='District', max_length=30)
	state = models.CharField(verbose_name='State', max_length=30)
	country = models.CharField(verbose_name='Country', max_length=30)

	def get_address(self):
		return f'{self.street}, {self.city}, {self.district}, {self.state}, {self.country} - {self.pin}'

	def __str__(self):
		return self.get_address()

	def save(self, *args, **kwargs):
		if self.state and self.country:
			self.state = self.state.capitalize()
			self.country = self.country.capitalize()
		super(CompanyAddress, self).save(*args, **kwargs)

	class Meta:
		verbose_name_plural = 'Company address'


class CompanyEmailHelpline(models.Model):
	company = models.ForeignKey(Company, on_delete=models.CASCADE)
	helpline = models.CharField(verbose_name='Helpline Type', max_length=20)
	email = models.EmailField(verbose_name='Email')

	def __str__(self):
		return f'{self.helpline} - {self.email}'

	class Meta:
		verbose_name_plural = 'Company email helpline'


class CompanyTelephoneHelpline(models.Model):
	company = models.ForeignKey(Company, on_delete=models.CASCADE)
	helpline = models.CharField(verbose_name='Helpline Type', max_length=20)
	telephone = models.CharField(verbose_name='Telephone', max_length=15)

	def __str__(self):
		return f'{self.helpline} - {self.telephone}'

	class Meta:
		verbose_name_plural = 'Company telephone helpline'


class CompanyFounder(models.Model):
	company = models.ForeignKey(Company, on_delete=models.CASCADE)
	name = models.CharField(verbose_name='Name', max_length=50)
	email = models.EmailField(verbose_name='Email')
	designation = models.CharField(verbose_name='Designation', max_length=30)
	profile_pic = models.ImageField(upload_to=profilepic_directory_path, verbose_name='Profile Pic')
	bio = models.TextField(verbose_name='About Founder')

	def __str__(self):
		return f'{self.name}, {self.designation}'


	def save(self, *args, **kwargs):
		if self.profile_pic:
			super(CompanyFounder, self).save(*args, **kwargs)
			img = Image.open(self.profile_pic.path)
			if img.height > 500 and img.width > 500:
				dim = (500, 500)
				img.thumbnail(dim)
			img.save(self.profile_pic.path, quality=100)
		super(CompanyFounder, self).save(*args, **kwargs)


class CustomerQuery(models.Model):
	company = models.ForeignKey(Company, on_delete=models.CASCADE)
	name = models.CharField(verbose_name='Customer Name', max_length=60)
	email = models.EmailField(verbose_name='Email')
	date_posted = models.DateTimeField(auto_now_add=True)
	subject = models.CharField(verbose_name='Subject', max_length=255)
	content = models.TextField(verbose_name='Content')

	def __str__(self):
		return f'{self.email} - {self.subject}'

	class Meta:
		verbose_name_plural = 'Customer query'


class CompanyFaq(models.Model):
	company = models.ForeignKey(Company, on_delete=models.CASCADE)
	question = models.TextField(verbose_name='Question')
	answer = RichTextField()
	asked_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.question

	class Meta:
		verbose_name_plural = 'Customer faq'


class CompanyReview(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	review = models.TextField(verbose_name='Review')
	rating = models.PositiveIntegerField(verbose_name='Rating')
	date_reviewed = models.DateTimeField(verbose_name='Review Date', auto_now_add=True)
	highlight = models.BooleanField(verbose_name='Highlight this Review', default=False)

	def __str__(self):
		return f'{self.user.username} rated {self.rating} star'

	def save(self, *args, **kwargs):
		if self.rating <= 0:
			self.rating = 0
		elif self.rating > 5:
			self.rating = 5
		super(CompanyReview, self).save(*args, **kwargs) 



class CompanyTermsCondition(models.Model):
	company = models.OneToOneField(Company, on_delete=models.CASCADE)
	terms_text = RichTextField()
	date_created = models.DateTimeField(auto_now_add=True)
	date_modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		return 'Terms & Condition'

	class Meta:
		verbose_name_plural = 'Terms & Condition'



class CompanyPrivacyPolicy(models.Model):
	company = models.OneToOneField(Company, on_delete=models.CASCADE)
	privacy_text = RichTextField()
	date_created = models.DateTimeField(auto_now_add=True)
	date_modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		return 'Privacy Policy'

	class Meta:
		verbose_name_plural = 'Privacy policy'


company/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib import messages

# Models
from company.models import Company, CustomerQuery, CompanyReview, CompanyFaq

# Decorators
from cookie.decorators import check_login_cookie



@check_login_cookie
def about(request):
	company = Company.objects.first()
	founders = company.companyfounder_set.all()
	context = {'company':company, 'founders':founders}
	return render(request, 'company/about.html', context)


@check_login_cookie
def contact(request):
	company = Company.objects.first()
	company_address = company.companyaddress.get_address()
	company_support_email = company.companyemailhelpline_set.all().get(helpline='support')
	company_telephone = company.companytelephonehelpline_set.all().get(helpline='call')
	context = {
		'address':company_address, 
		'support_email': company_support_email, 
		'telephone': company_telephone
	}
	
	if request.POST:
		company = Company.objects.first()
		customer_name = request.POST.get('mailer-name')
		customer_email = request.POST.get('mailer-email')
		mail_subject = request.POST.get('mail-subject')
		mail_content = request.POST.get('mail-content')
		customer_query = company.customerquery_set.create(name=customer_name, email=customer_email, subject=mail_subject, content=mail_content)

		messages.success(request, 'Thankyou for reaching us.')

	return render(request, 'company/contact.html', context)


@check_login_cookie
def faq(request):
	return render(request, 'company/faq.html')


def fetch_faq(request):
	if request.POST:
		faqs = CompanyFaq.objects.all()
		faqs_arr = []

		for faq in faqs:
			faq_obj = {}
			faq_obj['question'] = faq.question
			faq_obj['answer'] = faq.answer
			
			faqs_arr.append(faq_obj);

		return JsonResponse(faqs_arr, safe=False)
	return HttpResponse("Your are not authorized to access this page.") 


@check_login_cookie
def write_about_us(request):
	if request.POST:
		""" Get input from the user """
		review = request.POST.get('reviewer-thought')
		rating = int(request.POST.get('reviewer-rating'))
		
		if rating<0 or rating>5:
			messages.warning(request, 'Rating is not in valid range (0-5)')
		else:
			company_review = CompanyReview.objects.create(user=request.user, review=review, rating=rating)
			messages.success(request, 'Thankyou for your honest Review')

	return render(request, 'company/wba.html')


def redirect_default(request):
	return redirect('company:about')





company/templates/company/about.html
{% extends 'home/base.html' %}

{% load static %}



{% block title %}

  <title>About Us | ALINETER</title>

{% endblock title %}



{% block seo_metatag %}
  <meta name="description" content="This online SEO cheat sheet lists everyting to rank first...">
  <meta name="keywords" content="seo,cheat,sheet">

  <meta property="og:site_name" content="Alineter">
  <meta property="og:title" content="0.1 seconds is all it takes">
  <meta property="og:description" content="What are the things people notice first to form a quick opinion on you? Here's your answer">
  <meta property="og:url" content="https://www.colbyfayock.com/2020/03/anyone-can-map-inspiration-and-an-introduction-to-the-world-of-mapping/">
  <meta property="og:type" content="article">

  <meta property="article:publisher" content="https://www.alineter.com"/>
  <meta property="article:section" content="Trending Design"/>
  <meta property="article:tag" content="Fashion"/>
  <meta property="article:published_time" content="2021-03-12T00:01:56+00:00" />
  <meta property="article:author" content="Sanmay Biswal"/>

  <meta property="og:image" content="https://mohit9090.github.io/alineter/images/blog-img--1.webp">
  <meta property="og:image:secure_url" content="https://mohit9090.github.io/alineter/images/blog-img--1.webp">
  <meta property="og:image:width" content="1280">
  <meta property="og:image:height" content="640">

  <meta property="twitter:card" content="What are the things people notice first to form a quick opinion on you? Here's your answer" />
  <meta property="twitter:image" content="https://mohit9090.github.io/alineter/images/blog-img--1.webp" />
  <meta property="twitter:site" content="ALINETER" />
{% endblock seo_metatag %}



{% block css_link %}
  
  <link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}?{% now 'U' %}">

{% endblock css_link %}



{% block page_content %}

  <!-- ================== ABOUT US ========================= -->

  <section id="about-us" class="w-100 scroll-reveal-content">
    <div class="container-fluid">
      <div class="text-center position-relative cx secondary-wrapper">
        <div class="head text-left">
          <h2 class="big-title reveal__from-bottom">About</h2>
        </div>
        <div class="body text-left">
          <p class="about-us-content reveal__from-bottom">
            <i><b>Alineter</b></i> is a new age fashion and lifestyle company that focuses on making you look confident and unique, so that you stand out from the crowd and be <b>READY FOR EVERY MOMENT.</b>

            Started by two young Fashion Enthusiasts in Bhubaneswar, Odisha with a goal to provide people with Premium Quality clothes without them having to give any stress to their wallet.
          </p>
        </div>

        <div class="head text-left reveal__from-bottom">
          <h2 class="small-title"><b>Here's what we bring to you:</b></h2>
        </div>
        <div class="text-left">
          <p class="about-us-content reveal__from-bottom">
            With our core belief that our <b>customers should always get the best and latest stuff,</b> we decided to do something different than others. (Difficult choice but we knew our customers would love it and that's what our main concern is.)
          </p>
          <ul class="">
            <li class="about-us-content mb-4 reveal__from-bottom"><b><i>Premium Designs </i></b>&nbsp;&nbsp;So that you can walk in confidence, stand out from the crowd and make your friends even more jealous.</li>
            <li class="about-us-content mb-4 reveal__from-bottom"><b><i>Best Price </i></b>&nbsp;&nbsp;One of our major goals was to deliver premium quality products at the best price possible so that you get the best without making a dent in your wallet, Hence we did.</li>
            <li class="about-us-content mb-4 reveal__from-bottom"><b><i>Customer Experience </i></b>&nbsp;&nbsp;that you feel in love with, (hope your girlfriend won't get jealous on us)</li>
            <li class="about-us-content mb-4 reveal__from-bottom"><b><i>Wide range of variety </i></b>&nbsp;&nbsp;so that you don't fall short on options. (we hate limits just like YOU do)</li>
            <li class="about-us-content mb-4 reveal__from-bottom"><b><i>Your very own Fashion Guide </i></b>&nbsp;&nbsp;Real fashion experts are hard to find. (Especially in INDIA, where everyone claims to be an expert) But don't worry we are there for you.

            We would help you to choose the clothes that would look best on you. And we promise you won't regret it.

          There's even more; but let's keep that a secret for now.</li>
          </ul>
        </div>

        <div class="body text-left ">
          <p class="about-us-content reveal__from-bottom"><b><i>Why you ask?</i></b><br>So that you can discover those added benefits after you make us a part of your lifestyle.</p>
        </div><br>

        <div class="head text-left ">
          <h2 class="small-title reveal__from-bottom"><b>Customers comes First</b></h2>
        </div>
        <div class="body text-left">
          <p class="about-us-content reveal__from-bottom">
            We are really serious when it comes to our <b>Customer's</b> needs, desires, and concerns. Therefore what's best for you is best for us.

            Every Product is made keeping you in mind so that you never miss out, stay in trend and always stand out from the crowd.

            We continuously work to provide the best clothes to our customers so that they keep looking <b>AWESOME!</b>
          </p>
        </div>

      </div>
    </div>
  </section> 


  <!-- ============== DIRECTORS SECTION ================== -->
  <section id="directors" class="w-100 scroll-reveal-content">
    <div class="container-fluid w-100">
      <h2 class="big-title text-center reveal__from-bottom">Directors</h2><br><br>
      <div class="profile-cards">
        <div class="row p-0 h-100">

          {% for founder in founders %}

            <div class="col-lg-6 col-md-6 col-sm-12 pt-3 pb-3">
              <div class="card profile-card {% if forloop.counter == 1 %}left{% elif forloop.counter == 2 %}right{% endif %}-card wrapper position-relative rounded">
                <img class="card-img-top profile-card-img reveal__opacity" src="/static{{ founder.profile_pic.url }}" alt="{{ founder.name }}, {{ founder.designation }}">
                <div class="card-body profile-card-body text-center">
                  <h2 class="small-title director-name reveal__from-bottom">{{ founder.name }}</h2>
                  <p class="director-designation reveal__from-bottom">{{ founder.designation }}</p>
                  <p class="director-bio text-left reveal__from-bottom about-us-content">{{ founder.bio }}</p>
                </div>
              </div>
            </div>

          {% endfor %}

      </div>
    </div>
  </section>  


  <!-- =============== SMALL DESCRIPTION ========================== -->

  <section id="small-description" class="w-100 scroll-reveal-content">
    <div class="container-fluid">
      <div class="text-center position-relative cx secondary-wrapper">
        <p class="font-weight-light about-us-content reveal__from-bottom">
          As amazing as this clothing industry is, we feel that it lacks some spice. We strive to bring changes for the betterment in the world of clothing. We want to set a new trend through our personalized designs. We bring you products that won’t make a dent in your pocket but will give that ever wanted satisfaction and comfort.
        </p>
      </div>
    </div>        
  </section>


  <!-- ================= ABOUT PRODUCTS SECTION ================= -->

  <section id="about-products" class="w-100 scroll-reveal-content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12 mt-4 order-lg-1 order-md-1 order-sm-2 left">
          <div class="pdModel-img-holder position-relative cxy load-gradient" id="pdModel-img">
            <img src="/static/images/alineter/model_pic_1859__white_tee_park__jpeg--30.jpg" class="pdModel-img img-cover reveal__opacity" onload="document.getElementById('pdModel-img').classList.remove('load-gradient')"/>
          </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 mt-4 order-lg-2 order-md-2 order-sm-1 right">
          <div class="body text-left text-richblack position-relative cy">
            <h2 class="medium-title font-weight-bold">Products</h2><br>
            <p class="about-us-content">Surely our aim is to develop outstanding products that the people will fall in love with. And for the starters, we are producing t-shirts for men which will make you stand-out from the crowd and make you look even more stylish.
            Not only will these clothes make you look more attractive, but these are surprisingly comfortable. They are made up of 100% cotton that will sit snuggly on your body. They will give you the sense of comfort you’ve always wanted in a t-shirt.
            These t-shirts aren’t just for some occasion. These are the all moment wear, made to spend every moment in. We strive to bring a one step solution for your clothing checklist.
            We bring you all of our outstanding products at such a price point that will hardly make a dent in your wallet. With that said, we are in no mind-set in compromising the quality and comfort. These t-shirts will take you to a whole new level of stunningness.
            We invite you to browse through our site to find just what you have been looking for.</p>
            <a href="{% url 'store:store' %}" class="btn btn-i-primary shop-btn">Visit Store</a>
          </div>
        </div>
      </div>
    </div>        
  </section>

{% endblock page_content %}



{% block js_script_link %}
  
  <script type="text/javascript">
    const scrollBtn = document.querySelectorAll(".scroll-btn");
    
    let isMobile = detectMob();
    isMobile ? addMobile__Class([...scrollBtn]) : removeMobile__Class([...scrollBtn]);
  </script>

{% endblock js_script_link %}

company/templates/company/wba.html
{% extends 'home/base.html' %}

{% load static %}



{% block title %}

  <title>Write About Us | Alineter</title>

{% endblock title %}



{% block seo_metatag %}
  <meta name="description" content="This online SEO cheat sheet lists everyting to rank first...">
  <meta name="keywords" content="seo,cheat,sheet">

  <meta property="og:site_name" content="Alineter">
  <meta property="og:title" content="0.1 seconds is all it takes">
  <meta property="og:description" content="What are the things people notice first to form a quick opinion on you? Here's your answer">
  <meta property="og:url" content="https://www.colbyfayock.com/2020/03/anyone-can-map-inspiration-and-an-introduction-to-the-world-of-mapping/">
  <meta property="og:type" content="article">

  <meta property="article:publisher" content="https://www.alineter.com"/>
  <meta property="article:section" content="Trending Design"/>
  <meta property="article:tag" content="Fashion"/>
  <meta property="article:published_time" content="2021-03-12T00:01:56+00:00" />
  <meta property="article:author" content="Sanmay Biswal"/>

  <meta property="og:image" content="https://mohit9090.github.io/alineter/images/blog-img--1.webp">
  <meta property="og:image:secure_url" content="https://mohit9090.github.io/alineter/images/blog-img--1.webp">
  <meta property="og:image:width" content="1280">
  <meta property="og:image:height" content="640">

  <meta property="twitter:card" content="What are the things people notice first to form a quick opinion on you? Here's your answer" />
  <meta property="twitter:image" content="https://mohit9090.github.io/alineter/images/blog-img--1.webp" />
  <meta property="twitter:site" content="ALINETER" />
{% endblock seo_metatag %}



{% block css_link %}
  
  <link rel="stylesheet" type="text/css" href="{% static 'css/policy-page.css' %}?{% now 'U' %}">

{% endblock css_link %}



{% block page_content %}
  
  <section id="company-policy-wrapper" class="write-about-us w-100 scroll-reveal-content">
    <div class="container-fluid">

      <div class="secondary-wrapper mx-auto p-0">

        {% if request.user.is_authenticated %}
          
          {% if not messages %}
            
            <div class="wba-container text-center">
              <div class="policy-head--s1 reveal__from-bottom">
                <h1>Write About Us</h1>
              </div>
            </div>

            <div class="wba-form-wrapper">
              <form id="wba-form" method="post" action="{% url 'company:write_about_us' %}">
                {% csrf_token %}
                <!-- <div class="row">
                  <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="form-group reveal__from-bottom">
                      <label for="reviewer-name" class="auth-label">Your Name</label>
                      <input type="text" class="input--s2 w-100 auth-input reviewer-name" name="reviewer-name" id="reviewer-name" placeholder="Name Surname" required spellcheck="false" onkeyup="ifValid(this, 0)" maxlength="30">
                      <small class="help-text" for="reviewer-name"></small>
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="form-group reveal__from-bottom">
                      <label for="reviewer-email" class="auth-label">Your Email</label>
                      <input type="email" class="input--s2 w-100 auth-input reviewer-email" name="reviewer-email" id="reviewer-email" placeholder="mahitkumar166@gmail.com" required spellcheck="false" onkeyup="ifValid(this, 2)">
                      <small class="help-text" for="reviewer-email"></small>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-12">
                    <div class="form-group reveal__from-bottom">
                      <label for="reviewer-profilepic" class="auth-label">Profile Photo (optional)</label>
                      <input type="file" class="input--s2 w-100 auth-input reviewer-profilepic" name="reviewer-profilepic" id="reviewer-profilepic" onchange="validateImage(this)">
                      <small class="help-text" for="reviewer-profilepic">Allowed file format are jpg, jpeg and png</small>
                    </div>
                  </div>
                </div> -->

                <div class="row">
                  <div class="col-12">
                    <div class="form-group reveal__from-bottom">
                      <label for="reviewer-thought" class="auth-label">Your Experience with Us</label>
                      <textarea class="textarea--s1 w-100 auth-input reviewer-thought" rows=7 name="reviewer-thought" id="reviewer-thought" placeholder="In less than two small paragraphs, describe your expreience about using our website Alineter" required spellcheck="false" onkeyup="ifValid(this, 0)"></textarea>
                      <small class="help-text" for="reviewer-thought"></small>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-12">
                    <div class="form-group reveal__from-bottom text-center">
                      <label for="reviewer-rating" class="auth-label">Leave us a Rating</label>
                      <input type="number" class="input--s2 w-100 d-none auth-input" name="reviewer-rating" id="reviewer-rating" required>
                      <div class="rating-box mx-auto">
                        <div class="d-flex justify-content-center flex-wrap">
                          <i class="fa fa-star rating-icon" data-rating="1" onmouseover="starHover__on(this)" onmouseout="starHover__off(this)" onclick="selectStar(this)"></i>
                          <i class="fa fa-star rating-icon" data-rating="2" onmouseover="starHover__on(this)" onmouseout="starHover__off(this)" onclick="selectStar(this)"></i>
                          <i class="fa fa-star rating-icon" data-rating="3" onmouseover="starHover__on(this)" onmouseout="starHover__off(this)" onclick="selectStar(this)"></i>
                          <i class="fa fa-star rating-icon" data-rating="4" onmouseover="starHover__on(this)" onmouseout="starHover__off(this)" onclick="selectStar(this)"></i>
                          <i class="fa fa-star rating-icon" data-rating="5" onmouseover="starHover__on(this)" onmouseout="starHover__off(this)" onclick="selectStar(this)"></i>
                        </div>
                      </div>                      
                    </div>
                  </div>
                </div>

                <div class="row mt-5">
                  <div class="col-12">
                    <div class="form-group reveal__from-bottom text-center">
                      <button type="button" class="btn review-btn btn-i-primary w-50" onclick="validate_wbapage()">
                        <div class="d-flex justify-content-center" id="review-btn--div">
                          <span>Submit</span>
                        </div>
                      </button>
                    </div>
                  </div>
                </div>

              </form>              
            </div>

          {% else %}
            {% for message in messages %}
              <div class="wba-container text-center">
                <div class="policy-head--s1 reveal__from-bottom">
                  <img src="{% static 'images/alineter/alineter-w.png' %}" class="img-fluid" width=35 height=35>
                  <h1 class="mt-2">{{ message }}</h1>
                  <a href="" class="btn review-btn btn-i-primary mt-5"><span class="fa fa-home">&nbsp;</span>Home</a>
                </div>
              </div>
            {% endfor %}
          {% endif %}

        {% else %}

        <div class="wba-container text-center">
          <div class="policy-head--s1 reveal__from-bottom">
            <h1>You need to be our customer</h1>
            <div class="d-flex flex-column mt-5 p-3">
              <a href="{% url 'auth:signup' %}" class="btn review-btn btn-o-primary w-50 mx-auto mt-3">Signup</a>
              <a href="{% url 'auth:login' %}" class="btn review-btn btn-i-primary w-50 mx-auto mt-3">Login</a>
            </div>
          </div>
        </div>

        {% endif %}

      </div>

    </div>
  </section>

{% endblock page_content %}



{% block js_script_link %}

  <script type="text/javascript" src="{% static 'js/wba.js' %}?{% now 'U' %}"></script>

  <script type="text/javascript">
    const scrollBtn = document.querySelectorAll(".scroll-btn");
      
    let isMobile = detectMob();
    isMobile ? addMobile__Class([...scrollBtn]) : removeMobile__Class([...scrollBtn]);
  </script>

{% endblock js_script_link %}