alineter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('auth/', include('auth_page.urls')),
    path('blog/', include('blog.urls')),  
    path('cart/', include('cart.urls')),
    path('company/', include('company.urls')),  
    path('company/policy/', include('company_policy.urls')),  
    path('', include('home.urls')),  
    path('store/', include('store.urls'))
]


from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# ERR_HANDLER URL
from django.conf.urls import handler404, handler403, handler404, handler500

handler400 = 'ERROR_HANDLER.views.err_400'
handler403 = 'ERROR_HANDLER.views.err_403'
handler404 = 'ERROR_HANDLER.views.err_404'
handler500 = 'ERROR_HANDLER.views.err_500'

blog/urls.py
from django.urls import path
from . import views 

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
]

company_policy/urls.py
from django.urls import path
from . import views 

app_name = 'policy'

urlpatterns = [
    path('', views.redirect_default, name='redirect_default'),
    path('cancellation-refund/', views.cancellation_refund, name='cancellation_refund'),
    path('terms-condition/', views.terms_condition, name='terms_condition'),
    path('ordering-terms/', views.ordering_terms, name='ordering_terms')
]

home/urls.py
from django.urls import path
from . import views 

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('company_reviews/', views.company_reviews, name='company_reviews'),
    path('reviews_stats/', views.reviews_stats, name='reviews_stats')
]

ERROR_HANDLER/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect

# For Testing
# from django.test import SimpleTestCase, override_settings



def err_400(request, exception=None):
	context = {
		'error':{
			'code':400,
			'message':'Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.'
		}
	}
	return render(request, 'ERROR_HANDLER/error.html', context)


def err_403(request, exception=None):
	context = {
		'error':{
			'code':403,
			'message':'The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401, the client\'s identity is known to the server.'
		}
	}
	return render(request, 'ERROR_HANDLER/error.html', context)


def err_404(request, exception=None):
	context = {
		'error':{
			'code':404,
			'message':'The server can not find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 to hide the existence of a resource from an unauthorized client. This response code is probably the most famous one due to its frequent occurrence on the web.'
		}
	}
	return render(request, 'ERROR_HANDLER/error.html', context)

def err_500(request, exception=None):
	context = {
		'error':{
			'code':500,
			'message':'The server can not find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 to hide the existence of a resource from an unauthorized client. This response code is probably the most famous one due to its frequent occurrence on the web.'
		}
	}
	return render(request, 'ERROR_HANDLER/error.html', context)

ERROR_HANDLER/templates/ERROR_HANDLER/error.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% load static %}

  <title>Page not found 404 - Alineter</title>

  <meta link-colorarset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#000">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

  <!-- FAVICON -->
  <link rel="icon" href="images/alineter-b.png">

  <!-- SCROLL REVEAL LINK -->
  <script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>

  <!-- FONT AWESOME LINK -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!--GOOGLE FONTS-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;300;400;600&family=Nunito:wght@200;300;400;700;800&family=Open+Sans:wght@300;400;600;800&family=Roboto:wght@100;300;400&display=swap" rel="stylesheet">

  <!-- EXTERNAL CSS LINKS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}?{% now 'U' %}">
  <link rel="stylesheet" href="{% static 'css/error.css' %}?{% now 'U' %}">


</head>

<body>

  <section id="body">    

    <section id="page-content" class="position-relative">


      <!-- ERROR SECTION -->
      <section id="error-wrapper" class="w-100">
        <div class="container-fluid">
          <div class="error">
            <div class="row">
              <div class="col-lg-6 col-md-6 col-sm-12 error-catch">
                <div class="d-flex flex-column cy position-relative">
                  <h1 class="display-1 font-weight-bold txt-primary error-code">{{ error.code }}</h1>
                  <h1 class="display-4 txt-grey">Oops!</h1>
                  <br>
                  <!-- <p class="error-text txt-light">You may have picked the wrong door because I haven't been able to lay my eye on the page you've been searching for.</p> -->
                  <p class="error-text txt-light">{{ error.message }}</p>
                  <br>
                  <a href="{% url 'home:home' %}" class="btn btn-i-primary error-btn btn-lg rounded">Take me Home</a>
                </div>  
              </div>
              <div class="col-lg-6 col-md-6 error-graphics">
                <div class="position-relative cy">
                  <img src="/static/images/alineter/robot.png" class=""/>
                </div>
              </div>
            </div>
          </div>
        </div>        
      </section>


      <!--Copyright Section-->
      <footer id="copyright-section">
        <div class="copyright-wrapper text-center">
          <div class="container-fluid">
            <small>
              <span>&copy;2020-<span id="copyright-year"></span></span>
              <span><a href="{% url 'home:home' %}" class="link s-2">Alineter</a></span>
              <span>All Rights Reserved.</span>
              <span><a href="{% url 'policy:terms_condition' %}" class="link s-2">Terms of Use</a></span>
              <span>|</span>
              <span><a href="{% url 'policy:terms_condition' %}" class="link s-2">Privacy Policy</a></span>
            </small>
          </div>
         <script>
            let year=new Date().getFullYear().toString().slice(2);
            document.getElementById("copyright-year").innerHTML = year;
          </script>
        </div>
      </footer>
      



    </section><!--Page Content-->

  </section><!--Body-->


</body>
</html>
